### ISSUE TITLE
Bug, during report creating process

### ISSUE THREAD

**Issue by alexandrtrenkenshu** [QuantConnect/LeanReportCreator#4]
I did all steps  that were in  description. But at the end of report creating process I got the following message about error: Error in parse_con(txt, bigint_as_char) :parse error: premature EOF.

**Comment by multidis** [comment]
I had the same thing. Just add an empty line at the end of those files. There is also `profile.txt` vs. `Profile.txt`, the error message will tell you where.

**Comment by jaredbroad** [comment]
We gutted and rewrote the whole thing in python over the last 2 months to make deploying and modifying easier. Will close this as it relates to the old version -- if the issue persists please feel free to reopen
