### ISSUE TITLE
Cumulative return calculation for time interval subsets

### ISSUE THREAD

**Issue by multidis** [QuantConnect/LeanReportCreator#6]
Please double-check Report Creator code for generating crisis plots. The problem seems to be around here:
https://github.com/QuantConnect/LeanReportCreator/blob/master/functions/event.R#L107

When subsetting a time interval, cumulative return difference as calculated appears to be relative to the initial time of the backtest, not the initial time of the subset interval. This could be confusing when e.g. 100% exposure to the benchmark would bring different growth than the benchmark, over a selected time subset.

**Comment by jaredbroad** [comment]
We gutted and rewrote the whole thing in python over the last 2 months to make deploying and modifying easier. Will close this as it relates to the old version -- if the issue persists please feel free to reopen
